frontend:
  image:
    repository: mauriciotoapanta/frontend
    tag: latest
backend-api:
  image:
    repository: mauriciotoapanta/backend-api
    tag: latest
backend-data:
  image:
    repository: mauriciotoapanta/backend-data
    tag: latest
mongodb:
  image:
    repository: mongo
    tag: 6