apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-data
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-data
  template:
    metadata:
      labels:
        app: backend-data
    spec:
      containers:
        - name: backend-data
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/comentarios"
