apiVersion: v2
name: proyecto-final
description: Umbrella chart for Sistema de Comentarios
version: 0.1.0
type: application
dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://../frontend"
  - name: backend-api
    version: 0.1.0
    repository: "file://../backend-api"
  - name: backend-data
    version: 0.1.0
    repository: "file://../backend-data"
  - name: mongodb
    version: 0.1.0
    repository: "file://../mongodb"
